src/Entity/Articles.php
<?php

namespace App\Entity;

use App\Repository\ArticlesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticlesRepository::class)]
class Articles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 70)]
    private ?string $Titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Contenu = null;

    #[ORM\Column(length: 255)]
    private ?string $Image = null;

    #[ORM\Column]
    private ?bool $Public = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function isPublic(): ?bool
    {
        return $this->Public;
    }

    public function setPublic(bool $Public): self
    {
        $this->Public = $Public;

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Form\MessageType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Articles;
use App\Entity\Message;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Translation\MessageCatalogue;


class BlogController extends AbstractController
{
    #[Route('/', name: 'app_blog')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $articles = $entityManager->getRepository(Articles::class)->findAll();
        return $this->render('blog/index.html.twig', ['articles' => $articles]);
    }

    #[Route('/aPropos', name: 'app_aPropos')]
    public function aPropos(): Response
    {
        return $this->render('blog/aPropos.html.twig', [
            'controller_name' => 'À propos',
        ]);
    }
    
    #[Route('/prestations', name: 'app_prestations')]
    public function prestations(): Response
    {
        return $this->render('blog/prestations.html.twig', [
            'controller_name' => 'Les prestations',
        ]);
    }

    #[Route('/ateliers', name: 'app_ateliers')]
    public function ateliers(): Response
    {
        return $this->render('blog/ateliers.html.twig', [
            'controller_name' => 'Les ateliers',
        ]);
    }

    #[Route('/rdv', name: 'app_rdv')]
    public function rdv(): Response
    {
        return $this->render('blog/rdv.html.twig', [
            'controller_name' => 'Rendez-vous',
        ]);
    }

      
    #[Route('/contact', name: 'app_contact')]
    public function contact(): Response
    {
        $Message = new Message();
        $contactForm = $this->createForm(MessageType::class, $Message);
        return $this->render('blog/contact.html.twig', ['contactform'=>$contactForm
        ]);
    }

    
   

}

templates/blog/aPropos.html.twig
{% extends 'base.html.twig' %}


{% block title %}Cdemoiselles{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 'playfair display'; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>


<div class="example-wrapper">
    <h1>{{ controller_name }}</h1>

   <!--Partie principale du site-->
<style>
.portrait {
    height: 200px;
    display: flex;
    align-items: center;
    justify-content: center;
}

</style>
<main>
  <div class="container p-3 my-3 border" id="descriptif">
  <p>Je suis Marie-Anne GIRARDET, professeur d'activité physique adaptée & conseillère en image certifiée à Lyon. 
  <br>
  Depuis toujours j'ai ce plaisir d'écouter, de conseiller, et de soutenir des femmes en quête de renouveau.
  <br>
  Je suis convaincue que l'activité physique & la mode ont des points communs : tous les deux cultivent notre estime de soi & favorisent une bonne santé physique et mentale.
  <br>
  C'est pourquoi, j'ai souhaité créer le concept innovant <i>Cdemoiselles</i>, alliant mes deux passions. <br>
  Je peux ainsi aider les femmes à s'aimer, se dépasser et s'accepter comme elles sont, en améliorant le regard et l'image qu'elles ont d'elles-mêmes.
  <br>
  Par le biais des techniques de coaching en image & un accompagnement sportif personnalisé, je vous emmène vers une meilleure et plus juste version de vous-même. 
  </p>
  <br>
  <div class="container" id="portrait">
  <img src="Images/MA/Portrait 4.jpg" width="650" height="675" alt="Portrait">
</div>
<br>
  <p>  <a href="{{ url('app_prestations') }}" title="Prestations">Plus d'informations</a>
</div>
  </main>
  <br>
  <br>
   <!--<ul>
        <li>Your controller at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/src/Controller/BlogController.php'|file_link(0) }}">src/Controller/BlogController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/templates/blog/index.html.twig'|file_link(0) }}">templates/blog/index.html.twig</a></code></li>
    </ul>-->
</div>
{% endblock %}

templates/blog/ateliers.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cdemoiselles{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 'playfair display'; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>{{ controller_name }}</h1>

    <main>
<div class="container text-center">
  <div class="row row-cols-3">
    <div class="col"> 
        <div class="card mb-2" style="width: 18rem;">
          <img src="Images/Ateliers/colo.jpg" class="card-img-top" alt="Atelier colorimétrie">
          <div class="card-body">
            <h5 class="card-title">Atelier colorimétrie</h5>
            <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur excepturi, nesciunt provident quisquam nihil natus beatae dignissimos necessitatibus vero!</p><a href="priseRDV.php" class="btn btn-light">Je veux !</a>
          </div>
        </div>
    </div>
    <br>
    <div class="col"> 
        <div class="card mb-2" style="width: 18rem;">
        <img src="Images/Ateliers/coloEVJF.jpg" class="card-img-top" alt="Atelier colorimétrie EVJF">
              <div class="card-body">
                <h5 class="card-title mb-2">Atelier colorimétrie - Spécial EVJF</h5>
            <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur excepturi, nesciunt provident quisquam nihil natus beatae dignissimos necessitatibus vero!</p><a href="priseRDV.php" class="btn btn-light">Je veux !</a>
          </div>
        </div>
    </div>
    <br>
    <div class="col"> 
        <div class="card mb-2" style="width: 18rem;">
        <img src="Images/Ateliers/shoppinggroupe.jpg" class="card-img-top" alt="Atelier shopping et diagnostic morpho">
              <div class="card-body">
                <h5 class="card-title">Accompagnement shopping (groupe) et diagnostic morphologie</h5>
            <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur excepturi, nesciunt provident quisquam nihil natus beatae dignissimos necessitatibus vero!</p><a href="priseRDV.php" class="btn btn-light">Je veux !</a>
          </div>
        </div>
    </div>
    <br>
    <div class="col"> 
        <div class="card mb-2" style="width: 18rem;">
        <img src="Images/Ateliers/shoppingmariage.jpg" class="card-img-top" alt="Atelier shopping mariage">
                  <div class="card-body">
                    <h5 class="card-title">Accompagnement shopping - Spécial mariée et demoiselle d'honneur</h5>
            <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur excepturi, nesciunt provident quisquam nihil natus beatae dignissimos necessitatibus vero!</p><a href="priseRDV.php" class="btn btn-light">Je veux !</a>
          </div>
        </div>
    </div>
    <br>
  </div>
</div>
</main>
    <!--<ul>
        <li>Your controller at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/src/Controller/BlogController.php'|file_link(0) }}">src/Controller/BlogController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/templates/blog/index.html.twig'|file_link(0) }}">templates/blog/index.html.twig</a></code></li>
    </ul>-->
</div>
{% endblock %}

templates/blog/conditionsGenerelesUtilisation.html.twig
{% extends 'base.html.twig' %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 'playfair display'; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

{% block title %}Hello BlogController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Bonjour {{ controller_name }}! ✅</h1>

   <!--Partie principale du site-->
<style>
.portrait {
    height: 200px;
    display: flex;
    align-items: center;
    justify-content: center;
}

</style>
<main>
  <div class="container p-3 my-3 border" id="descriptif">
  <p>Je suis Marie-Anne GIRARDET, professeur d'activité physique adaptée & conseillère en image certifiée à Lyon. 
  <br>
  Depuis toujours j'ai ce plaisir d'écouter, de conseiller, et de soutenir des femmes en quête de renouveau.
  <br>
  Je suis convaincue que l'activité physique & la mode ont des points communs : tous les deux cultivent notre estime de soi & favorisent une bonne santé physique et mentale.
  <br>
  C'est pourquoi, j'ai souhaité créer le concept innovant <i>Cdemoiselles</i>, alliant mes deux passions. <br>
  Je peux ainsi aider les femmes à s'aimer, se dépasser et s'accepter comme elles sont, en améliorant le regard et l'image qu'elles ont d'elles-mêmes.
  <br>
  Par le biais des techniques de coaching en image & un accompagnement sportif personnalisé, je vous emmène vers une meilleure et plus juste version de vous-même. 
  </p>
  <br>
  <div class="container" id="portrait">
  <img src="Images/MA/Portrait 4.jpg" width="650" height="675" alt="Portrait">
</div>
<br>
  <p>  <a href="prestations.php" class="btn btn-light">Plus d'informations</a>
</div>
  </main>
  <br>
  <br>
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/src/Controller/BlogController.php'|file_link(0) }}">src/Controller/BlogController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/templates/blog/index.html.twig'|file_link(0) }}">templates/blog/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/blog/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cdemoiselles{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 'playfair display'; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<main> 
<div class="example-wrapper">

    <h3>Une question ? N'hésitez pas à me contacter ! &#128140</h3>

{{form(contactform)}}
 
    
            <br>
            <br>
            <div class="submit">
                <div class="submit__acceptrgpd">
                    <input type="checkbox" name="rgpd" id="rgpd">
                    <label for="rgpd"><i>En cochant cette case, vou acceptez que vos données personnelles soient traitées par notre équipe commerciale. Vous acceptez également nos <a href="conditionsGeneralesUtilisation">Conditions Générales d'Utilisation.</a></i></label>
                </div>
            </p>
                <br>
                <br>
                <div class="submit__btn">
                    <input type="submit" value="Envoyer le formulaire">
                </div>
            </div>
        </form>
  
    <br>
    <br>
    <div id="wrapper-9cd199b9cc5410cd3b1ad21cab2e54d3">
      <div id="map-9cd199b9cc5410cd3b1ad21cab2e54d3"></div><script>(function () {
          var setting = {"height":531,"width":803,"zoom":17,"queryString":"Rue des Chanets, Dannemarie-sur-Crête, France","place_id":"Ei5SdWUgZGVzIENoYW5ldHMsIERhbm5lbWFyaWUtc3VyLUNyw6p0ZSwgRnJhbmNlIi4qLAoUChIJZ_mjuUNnjUcRIJzyGEO614ESFAoSCVfPpj9AZ41HET4Afsf4d0VY","satellite":false,"centerCoord":[47.20478191715202,5.869388799999995],"cid":"0x81d7ba4318f29c20","lang":"fr","cityUrl":"/france/besancon-9363","cityAnchorText":"Carte de Besançon, Franche-Comte, France","id":"map-9cd199b9cc5410cd3b1ad21cab2e54d3","embed_id":"922127"};
          var d = document;
          var s = d.createElement('script');
          s.src = 'https://1map.com/js/script-for-user.js?embed_id=922127';
          s.async = true;
          s.onload = function (e) {
            window.OneMap.initMap(setting)
          };
          var to = d.getElementsByTagName('script')[0];
          to.parentNode.insertBefore(s, to);
        })();</script><a href="https://1map.com/fr/map-embed">1 Map</a></div>
    <br>
    <br>
  </div>
    </main>
   <!-- <ul>
        <li>Your controller at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/src/Controller/BlogController.php'|file_link(0) }}">src/Controller/BlogController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/templates/blog/index.html.twig'|file_link(0) }}">templates/blog/index.html.twig</a></code></li>
    </ul>
</div>-->
{% endblock %}

templates/blog/footer.html.twig
{% extends 'base.html.twig' %}




{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 'playfair display'; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
<!--Footer-->
<footer class="bg-transparent text-lg-start">
      <hr class="m-0" />

      <div class="text-center py-4 align-items-center">
        <p>On se retrouve sur les réseaux ?</p>
        <a
          href="https://www.facebook.com/people/Cdemoiselles/100082525371571/"
          class="btn btn-dark m-1"
          role="button"
          rel="nofollow"
          target="_blank"
          
        >
          <i class="fab fa-facebook-f"></i>
        </a>
        <a
          href="https://www.instagram.com/cdemoiselles/"
          class="btn btn-dark m-1"
          role="button"
          rel="nofollow"
          target="_blank"
       >
        <i class="bi bi-instagram"></i>
        </a>
      </div>

      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: #8C165D;">
      © 2023 Copyright: GAMING CAMPUS - FORMATION DWWM
      </div>
      <!-- Copyright -->
    </footer>
    <!--Footer-->


</body>

</html> 
{% endblock %}

templates/blog/header.html.twig
{% extends 'base.html.twig' %}




{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 'playfair display'; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<!DOCTYPE html>
<html lang="fr">

<head> <!--toutes les informations exploitées de l'extérieur (seo, navigateur, synthétiseur vocal ...)-->
    <meta charset="UTF-8"> <!--pour que le site soit compris partout dans le monde, notamment avec é,è etc-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- navigateurs pris en charge-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!--largeur d'écran, sans zoom avec la notion scale-->
    
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
     <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
     <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
     <link rel="stylesheet" type="text/css" href="styleCSS/style.css" /> 
        <title>Cdemoiselles - Coaching sportif et conseil en image</title> <!--titre de la page lors ouverture dans le navigateur-->
       
</head>

<?php 
?>
{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cdemoiselles{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 'playfair display'; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
          <!--Main Navigation-->

    <!--Main layout-->
    <main class="mt-5">
      <div class="container">
        <!--Section: Content-->
        <section>
          <div class="row">
            <div class="col-md-6 gx-5 mb-4">
              <div class="bg-image hover-overlay ripple shadow-2-strong rounded-5" data-mdb-ripple-color="light">
                <img src="Images/Illu/Illu.jpg" class="img-fluid" />
                <a href="#!">
                  <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                </a>
              </div>
            </div>

            <div class="col-md-6 gx-5 mb-4">
              <h4><strong>Ma vision des choses</strong></h4>
              <p class="text-muted">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis consequatur
                eligendi quisquam doloremque vero ex debitis veritatis placeat unde animi laborum
                sapiente illo possimus, commodi dignissimos obcaecati illum maiores corporis.
              </p>
              <p><strong>Plus qu'une histoire de style</strong></p>
              <p class="text-muted">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod itaque voluptate
                nesciunt laborum incidunt. Officia, quam consectetur. Earum eligendi aliquam illum
                alias, unde optio accusantium soluta, iusto molestiae adipisci et?
              </p>
            </div>
          </div>
        </section>
        <!--Section: Content-->

        <hr class="my-5" />

        <div id="carouselExample" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="Images/Illu/Illu2.jpg" class="d-block w-100"alt="Illu 2">
    </div>
    <div class="carousel-item">
      <img src="Images/Illu/Illu3.jpg" class="d-block w-100" alt="Illu 3">
    </div>
    <div class="carousel-item">
      <img src="Images/Illu/Illu4.jpg" class="d-block w-100" alt="Illu 4">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<br>
<br>
        <!--Section: Content-->
        <section class="text-center">
          <h4 class="mb-5"><strong>Les derniers articles</strong></h4>

          
        </section>
        <!--Section: Content-->

        <hr class="my-5" />

    
        <!--Section: Content-->
      </div>
    </main>
    <!--Main layout-->

    {% for article in articles %}
        {% if article.public %}
            {{article.titre}}
            {{article.contenu}}
            <br>
        {% endif %}
    {% endfor %}
    <!--<ul>
        <li>Your controller at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/src/Controller/BlogController.php'|file_link(0) }}">src/Controller/BlogController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/templates/blog/index.html.twig'|file_link(0) }}">templates/blog/index.html.twig</a></code></li>
    </ul>-->
</div>
{% endblock %}

templates/blog/leblog.html.twig
{% extends 'base.html.twig' %}


{% block title %}Cdemoiselles{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 'playfair display'; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>


<div class="example-wrapper">
    <h1>{{ controller_name }}</h1>

   <!--Partie principale du site-->
<style>
.portrait {
    height: 200px;
    display: flex;
    align-items: center;
    justify-content: center;
}

</style>
<main>
  <div class="container p-3 my-3 border" id="descriptif">
  <p>Je suis Marie-Anne GIRARDET, professeur d'activité physique adaptée & conseillère en image certifiée à Lyon. 
  <br>
  Depuis toujours j'ai ce plaisir d'écouter, de conseiller, et de soutenir des femmes en quête de renouveau.
  <br>
  Je suis convaincue que l'activité physique & la mode ont des points communs : tous les deux cultivent notre estime de soi & favorisent une bonne santé physique et mentale.
  <br>
  C'est pourquoi, j'ai souhaité créer le concept innovant <i>Cdemoiselles</i>, alliant mes deux passions. <br>
  Je peux ainsi aider les femmes à s'aimer, se dépasser et s'accepter comme elles sont, en améliorant le regard et l'image qu'elles ont d'elles-mêmes.
  <br>
  Par le biais des techniques de coaching en image & un accompagnement sportif personnalisé, je vous emmène vers une meilleure et plus juste version de vous-même. 
  </p>
  <br>
  <div class="container" id="portrait">
  <img src="Images/MA/Portrait 4.jpg" width="650" height="675" alt="Portrait">
</div>
<br>
  <p>  <a href="{{ url('app_prestations') }}" title="Prestations">Plus d'informations</a>
</div>
  </main>
  <br>
  <br>
   <!--<ul>
        <li>Your controller at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/src/Controller/BlogController.php'|file_link(0) }}">src/Controller/BlogController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/templates/blog/index.html.twig'|file_link(0) }}">templates/blog/index.html.twig</a></code></li>
    </ul>-->
</div>
{% endblock %}

templates/blog/politiqueConfidentialite.html.twig
{% extends 'base.html.twig' %}


{% block title %}Hello BlogController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 'playfair display'; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Bonjour {{ controller_name }}! ✅</h1>

   <!--Partie principale du site-->
<style>
.portrait {
    height: 200px;
    display: flex;
    align-items: center;
    justify-content: center;
}

</style>
<main>
  <div class="container p-3 my-3 border" id="descriptif">
  <p>Je suis Marie-Anne GIRARDET, professeur d'activité physique adaptée & conseillère en image certifiée à Lyon. 
  <br>
  Depuis toujours j'ai ce plaisir d'écouter, de conseiller, et de soutenir des femmes en quête de renouveau.
  <br>
  Je suis convaincue que l'activité physique & la mode ont des points communs : tous les deux cultivent notre estime de soi & favorisent une bonne santé physique et mentale.
  <br>
  C'est pourquoi, j'ai souhaité créer le concept innovant <i>Cdemoiselles</i>, alliant mes deux passions. <br>
  Je peux ainsi aider les femmes à s'aimer, se dépasser et s'accepter comme elles sont, en améliorant le regard et l'image qu'elles ont d'elles-mêmes.
  <br>
  Par le biais des techniques de coaching en image & un accompagnement sportif personnalisé, je vous emmène vers une meilleure et plus juste version de vous-même. 
  </p>
  <br>
  <div class="container" id="portrait">
  <img src="Images/MA/Portrait 4.jpg" width="650" height="675" alt="Portrait">
</div>
<br>
  <p>  <a href="prestations.php" class="btn btn-light">Plus d'informations</a>
</div>
  </main>
  <br>
  <br>
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/src/Controller/BlogController.php'|file_link(0) }}">src/Controller/BlogController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/laragon/www/Symfony/symfony/blog/templates/blog/index.html.twig'|file_link(0) }}">templates/blog/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}